"""empty message

Revision ID: a7d007e03c27
Revises: 
Create Date: 2019-03-21 14:06:58.017926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7d007e03c27'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('down_json',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('main', sa.String(length=500), nullable=True, comment='链接'),
    sa.Column('screenshot', sa.String(length=20), nullable=True, comment='截屏时间间隔'),
    sa.Column('maxtime', sa.String(length=20), nullable=True, comment='最大截屏个数'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('up_json',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.String(length=200), nullable=True, comment='UUID'),
    sa.Column('main', sa.String(length=500), nullable=True, comment='链接'),
    sa.Column('screen', sa.String(length=50), nullable=True, comment='容器分辨率'),
    sa.Column('point', sa.TEXT(), nullable=True, comment='点击位置数组'),
    sa.Column('button', sa.TEXT(), nullable=True, comment='返回键，左上角x按钮，数组'),
    sa.Column('jump', sa.TEXT(), nullable=True, comment='跳转链接数组'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('up_json')
    op.drop_table('down_json')
    # ### end Alembic commands ###
