"""empty message

Revision ID: eb36690eca01
Revises: a7d007e03c27
Create Date: 2019-03-22 10:51:27.170024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb36690eca01'
down_revision = 'a7d007e03c27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('up_json', sa.Column('times', sa.String(length=20), nullable=True, comment='上报次数'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('up_json', 'times')
    # ### end Alembic commands ###
